server:
  port: 8089

logging:
  level:
    org.springframework: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  messages:
    basename: messages
  devtools:
    livereload:
      enabled: true
  security:
    user:
      name: heidi
      password: pass00